
target 'Booster' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'FirebaseAuth'
pod 'FirebaseStorage'
pod 'FirebaseDatabase'
pod 'Alamofire'
pod 'AlamofireImage'
pod 'NewPopMenu'
end


